// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.3
// source: PBBattle.proto

//option optimize_for = LITE_RUNTIME;

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RightOpType int32

const (
	RightOpType_noop RightOpType = 0 //没有操作
	RightOpType_rop1 RightOpType = 1 //操作1
	RightOpType_rop2 RightOpType = 2 //操作2
	RightOpType_rop3 RightOpType = 3 //操作3
	RightOpType_rop4 RightOpType = 4 //操作4
	RightOpType_rop5 RightOpType = 5 //操作5
	RightOpType_rop6 RightOpType = 6 //操作6
	RightOpType_rop7 RightOpType = 7 //操作7
)

// Enum value maps for RightOpType.
var (
	RightOpType_name = map[int32]string{
		0: "noop",
		1: "rop1",
		2: "rop2",
		3: "rop3",
		4: "rop4",
		5: "rop5",
		6: "rop6",
		7: "rop7",
	}
	RightOpType_value = map[string]int32{
		"noop": 0,
		"rop1": 1,
		"rop2": 2,
		"rop3": 3,
		"rop4": 4,
		"rop5": 5,
		"rop6": 6,
		"rop7": 7,
	}
)

func (x RightOpType) Enum() *RightOpType {
	p := new(RightOpType)
	*p = x
	return p
}

func (x RightOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RightOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_PBBattle_proto_enumTypes[0].Descriptor()
}

func (RightOpType) Type() protoreflect.EnumType {
	return &file_PBBattle_proto_enumTypes[0]
}

func (x RightOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RightOpType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RightOpType(num)
	return nil
}

// Deprecated: Use RightOpType.Descriptor instead.
func (RightOpType) EnumDescriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{0}
}

type BattleUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      *int32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	BattleID *int32 `protobuf:"varint,2,req,name=battleID" json:"battleID,omitempty"`
	RoleID   *int32 `protobuf:"varint,3,req,name=roleID" json:"roleID,omitempty"`
}

func (x *BattleUserInfo) Reset() {
	*x = BattleUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleUserInfo) ProtoMessage() {}

func (x *BattleUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleUserInfo.ProtoReflect.Descriptor instead.
func (*BattleUserInfo) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{0}
}

func (x *BattleUserInfo) GetUid() int32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *BattleUserInfo) GetBattleID() int32 {
	if x != nil && x.BattleID != nil {
		return *x.BattleID
	}
	return 0
}

func (x *BattleUserInfo) GetRoleID() int32 {
	if x != nil && x.RoleID != nil {
		return *x.RoleID
	}
	return 0
}

type TcpEnterBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandSeed       *int32            `protobuf:"varint,1,req,name=randSeed" json:"randSeed,omitempty"`
	BattleUserInfo []*BattleUserInfo `protobuf:"bytes,2,rep,name=battleUserInfo" json:"battleUserInfo,omitempty"`
}

func (x *TcpEnterBattle) Reset() {
	*x = TcpEnterBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpEnterBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpEnterBattle) ProtoMessage() {}

func (x *TcpEnterBattle) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpEnterBattle.ProtoReflect.Descriptor instead.
func (*TcpEnterBattle) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{1}
}

func (x *TcpEnterBattle) GetRandSeed() int32 {
	if x != nil && x.RandSeed != nil {
		return *x.RandSeed
	}
	return 0
}

func (x *TcpEnterBattle) GetBattleUserInfo() []*BattleUserInfo {
	if x != nil {
		return x.BattleUserInfo
	}
	return nil
}

type UdpBattleReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      *int32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	BattleID *int32 `protobuf:"varint,2,req,name=battleID" json:"battleID,omitempty"`
	IsRecon  *bool  `protobuf:"varint,3,req,name=isRecon" json:"isRecon,omitempty"`
}

func (x *UdpBattleReady) Reset() {
	*x = UdpBattleReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpBattleReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpBattleReady) ProtoMessage() {}

func (x *UdpBattleReady) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpBattleReady.ProtoReflect.Descriptor instead.
func (*UdpBattleReady) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{2}
}

func (x *UdpBattleReady) GetUid() int32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *UdpBattleReady) GetBattleID() int32 {
	if x != nil && x.BattleID != nil {
		return *x.BattleID
	}
	return 0
}

func (x *UdpBattleReady) GetIsRecon() bool {
	if x != nil && x.IsRecon != nil {
		return *x.IsRecon
	}
	return false
}

type UdpBattleStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UdpBattleStart) Reset() {
	*x = UdpBattleStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpBattleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpBattleStart) ProtoMessage() {}

func (x *UdpBattleStart) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpBattleStart.ProtoReflect.Descriptor instead.
func (*UdpBattleStart) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{3}
}

type PlayerOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleID        *int32       `protobuf:"varint,1,req,name=battleID" json:"battleID,omitempty"`
	Move            *int32       `protobuf:"varint,2,req,name=move" json:"move,omitempty"`
	OperationID     *int32       `protobuf:"varint,3,req,name=operationID" json:"operationID,omitempty"`
	RightOperation  *RightOpType `protobuf:"varint,4,req,name=rightOperation,enum=pb.RightOpType" json:"rightOperation,omitempty"`
	OperationValue1 *int32       `protobuf:"varint,5,req,name=operationValue1" json:"operationValue1,omitempty"`
	OperationValue2 *int32       `protobuf:"varint,6,req,name=operationValue2" json:"operationValue2,omitempty"`
}

func (x *PlayerOperation) Reset() {
	*x = PlayerOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOperation) ProtoMessage() {}

func (x *PlayerOperation) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOperation.ProtoReflect.Descriptor instead.
func (*PlayerOperation) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerOperation) GetBattleID() int32 {
	if x != nil && x.BattleID != nil {
		return *x.BattleID
	}
	return 0
}

func (x *PlayerOperation) GetMove() int32 {
	if x != nil && x.Move != nil {
		return *x.Move
	}
	return 0
}

func (x *PlayerOperation) GetOperationID() int32 {
	if x != nil && x.OperationID != nil {
		return *x.OperationID
	}
	return 0
}

func (x *PlayerOperation) GetRightOperation() RightOpType {
	if x != nil && x.RightOperation != nil {
		return *x.RightOperation
	}
	return RightOpType_noop
}

func (x *PlayerOperation) GetOperationValue1() int32 {
	if x != nil && x.OperationValue1 != nil {
		return *x.OperationValue1
	}
	return 0
}

func (x *PlayerOperation) GetOperationValue2() int32 {
	if x != nil && x.OperationValue2 != nil {
		return *x.OperationValue2
	}
	return 0
}

type UdpUpPlayerOperations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MesID     *int32           `protobuf:"varint,1,req,name=mesID" json:"mesID,omitempty"`
	Operation *PlayerOperation `protobuf:"bytes,2,req,name=operation" json:"operation,omitempty"`
}

func (x *UdpUpPlayerOperations) Reset() {
	*x = UdpUpPlayerOperations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpUpPlayerOperations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpUpPlayerOperations) ProtoMessage() {}

func (x *UdpUpPlayerOperations) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpUpPlayerOperations.ProtoReflect.Descriptor instead.
func (*UdpUpPlayerOperations) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{5}
}

func (x *UdpUpPlayerOperations) GetMesID() int32 {
	if x != nil && x.MesID != nil {
		return *x.MesID
	}
	return 0
}

func (x *UdpUpPlayerOperations) GetOperation() *PlayerOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type AllPlayerOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operations []*PlayerOperation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
}

func (x *AllPlayerOperation) Reset() {
	*x = AllPlayerOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllPlayerOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPlayerOperation) ProtoMessage() {}

func (x *AllPlayerOperation) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPlayerOperation.ProtoReflect.Descriptor instead.
func (*AllPlayerOperation) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{6}
}

func (x *AllPlayerOperation) GetOperations() []*PlayerOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type UdpDownFrameOperations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameID    *int32              `protobuf:"varint,1,req,name=frameID" json:"frameID,omitempty"`
	Operations *AllPlayerOperation `protobuf:"bytes,2,req,name=operations" json:"operations,omitempty"`
}

func (x *UdpDownFrameOperations) Reset() {
	*x = UdpDownFrameOperations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpDownFrameOperations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpDownFrameOperations) ProtoMessage() {}

func (x *UdpDownFrameOperations) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpDownFrameOperations.ProtoReflect.Descriptor instead.
func (*UdpDownFrameOperations) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{7}
}

func (x *UdpDownFrameOperations) GetFrameID() int32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

func (x *UdpDownFrameOperations) GetOperations() *AllPlayerOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type UdpUpDeltaFrames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleID *int32  `protobuf:"varint,1,req,name=battleID" json:"battleID,omitempty"`
	Frames   []int32 `protobuf:"varint,2,rep,name=frames" json:"frames,omitempty"`
}

func (x *UdpUpDeltaFrames) Reset() {
	*x = UdpUpDeltaFrames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpUpDeltaFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpUpDeltaFrames) ProtoMessage() {}

func (x *UdpUpDeltaFrames) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpUpDeltaFrames.ProtoReflect.Descriptor instead.
func (*UdpUpDeltaFrames) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{8}
}

func (x *UdpUpDeltaFrames) GetBattleID() int32 {
	if x != nil && x.BattleID != nil {
		return *x.BattleID
	}
	return 0
}

func (x *UdpUpDeltaFrames) GetFrames() []int32 {
	if x != nil {
		return x.Frames
	}
	return nil
}

type UdpDownDeltaFrames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FramesData []*UdpDownFrameOperations `protobuf:"bytes,1,rep,name=framesData" json:"framesData,omitempty"`
}

func (x *UdpDownDeltaFrames) Reset() {
	*x = UdpDownDeltaFrames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpDownDeltaFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpDownDeltaFrames) ProtoMessage() {}

func (x *UdpDownDeltaFrames) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpDownDeltaFrames.ProtoReflect.Descriptor instead.
func (*UdpDownDeltaFrames) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{9}
}

func (x *UdpDownDeltaFrames) GetFramesData() []*UdpDownFrameOperations {
	if x != nil {
		return x.FramesData
	}
	return nil
}

type UdpUpGameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleID *int32 `protobuf:"varint,1,req,name=battleID" json:"battleID,omitempty"`
}

func (x *UdpUpGameOver) Reset() {
	*x = UdpUpGameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpUpGameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpUpGameOver) ProtoMessage() {}

func (x *UdpUpGameOver) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpUpGameOver.ProtoReflect.Descriptor instead.
func (*UdpUpGameOver) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{10}
}

func (x *UdpUpGameOver) GetBattleID() int32 {
	if x != nil && x.BattleID != nil {
		return *x.BattleID
	}
	return 0
}

type UdpDownGameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UdpDownGameOver) Reset() {
	*x = UdpDownGameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PBBattle_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UdpDownGameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpDownGameOver) ProtoMessage() {}

func (x *UdpDownGameOver) ProtoReflect() protoreflect.Message {
	mi := &file_PBBattle_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpDownGameOver.ProtoReflect.Descriptor instead.
func (*UdpDownGameOver) Descriptor() ([]byte, []int) {
	return file_PBBattle_proto_rawDescGZIP(), []int{11}
}

var File_PBBattle_proto protoreflect.FileDescriptor

var file_PBBattle_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x50, 0x42, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x56, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x68, 0x0a, 0x0e,
	0x54, 0x63, 0x70, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x08, 0x72, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x65, 0x64, 0x12, 0x3a, 0x0a, 0x0e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x58, 0x0a, 0x0e, 0x55, 0x64, 0x70, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e,
	0x22, 0x10, 0x0a, 0x0e, 0x55, 0x64, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x22, 0xf0, 0x01, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x37, 0x0a, 0x0e, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0e, 0x72, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x31, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x28, 0x0a, 0x0f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x06,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x60, 0x0a, 0x15, 0x55, 0x64, 0x70, 0x55, 0x70, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x65, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x65, 0x73, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a,
	0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x6a, 0x0a, 0x16, 0x55, 0x64, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x36, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x46,
	0x0a, 0x10, 0x55, 0x64, 0x70, 0x55, 0x70, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x12, 0x55, 0x64, 0x70, 0x44, 0x6f, 0x77,
	0x6e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0a,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x64, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x0d, 0x55, 0x64, 0x70, 0x55,
	0x70, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x64, 0x70, 0x44, 0x6f, 0x77, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x2a, 0x5d, 0x0a, 0x0b, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f, 0x6f, 0x70, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x70, 0x31, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x72,
	0x6f, 0x70, 0x32, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x70, 0x33, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x72, 0x6f, 0x70, 0x34, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x70,
	0x35, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x70, 0x36, 0x10, 0x06, 0x12, 0x08, 0x0a,
	0x04, 0x72, 0x6f, 0x70, 0x37, 0x10, 0x07,
}

var (
	file_PBBattle_proto_rawDescOnce sync.Once
	file_PBBattle_proto_rawDescData = file_PBBattle_proto_rawDesc
)

func file_PBBattle_proto_rawDescGZIP() []byte {
	file_PBBattle_proto_rawDescOnce.Do(func() {
		file_PBBattle_proto_rawDescData = protoimpl.X.CompressGZIP(file_PBBattle_proto_rawDescData)
	})
	return file_PBBattle_proto_rawDescData
}

var file_PBBattle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PBBattle_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_PBBattle_proto_goTypes = []interface{}{
	(RightOpType)(0),               // 0: pb.RightOpType
	(*BattleUserInfo)(nil),         // 1: pb.BattleUserInfo
	(*TcpEnterBattle)(nil),         // 2: pb.TcpEnterBattle
	(*UdpBattleReady)(nil),         // 3: pb.UdpBattleReady
	(*UdpBattleStart)(nil),         // 4: pb.UdpBattleStart
	(*PlayerOperation)(nil),        // 5: pb.PlayerOperation
	(*UdpUpPlayerOperations)(nil),  // 6: pb.UdpUpPlayerOperations
	(*AllPlayerOperation)(nil),     // 7: pb.AllPlayerOperation
	(*UdpDownFrameOperations)(nil), // 8: pb.UdpDownFrameOperations
	(*UdpUpDeltaFrames)(nil),       // 9: pb.UdpUpDeltaFrames
	(*UdpDownDeltaFrames)(nil),     // 10: pb.UdpDownDeltaFrames
	(*UdpUpGameOver)(nil),          // 11: pb.UdpUpGameOver
	(*UdpDownGameOver)(nil),        // 12: pb.UdpDownGameOver
}
var file_PBBattle_proto_depIdxs = []int32{
	1, // 0: pb.TcpEnterBattle.battleUserInfo:type_name -> pb.BattleUserInfo
	0, // 1: pb.PlayerOperation.rightOperation:type_name -> pb.RightOpType
	5, // 2: pb.UdpUpPlayerOperations.operation:type_name -> pb.PlayerOperation
	5, // 3: pb.AllPlayerOperation.operations:type_name -> pb.PlayerOperation
	7, // 4: pb.UdpDownFrameOperations.operations:type_name -> pb.AllPlayerOperation
	8, // 5: pb.UdpDownDeltaFrames.framesData:type_name -> pb.UdpDownFrameOperations
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_PBBattle_proto_init() }
func file_PBBattle_proto_init() {
	if File_PBBattle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PBBattle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcpEnterBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpBattleReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpBattleStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpUpPlayerOperations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllPlayerOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpDownFrameOperations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpUpDeltaFrames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpDownDeltaFrames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpUpGameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PBBattle_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UdpDownGameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PBBattle_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PBBattle_proto_goTypes,
		DependencyIndexes: file_PBBattle_proto_depIdxs,
		EnumInfos:         file_PBBattle_proto_enumTypes,
		MessageInfos:      file_PBBattle_proto_msgTypes,
	}.Build()
	File_PBBattle_proto = out.File
	file_PBBattle_proto_rawDesc = nil
	file_PBBattle_proto_goTypes = nil
	file_PBBattle_proto_depIdxs = nil
}
