// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.3
// source: PBCommon.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CSID int32

const (
	CSID_TCP_LOGIN                CSID = 1  //TcpLogin
	CSID_TCP_REQUEST_MATCH        CSID = 10 //TcpRequestMatch
	CSID_TCP_CANCEL_MATCH         CSID = 11 //TcpCancelMatch
	CSID_UDP_BATTLE_READY         CSID = 51 //UdpBattleReady
	CSID_UDP_UP_PLAYER_OPERATIONS CSID = 53 //UdpUpPlayerOperations
	CSID_UDP_UP_DELTA_FRAMES      CSID = 55 //UdpUpDeltaFrames
	CSID_UDP_UP_GAME_OVER         CSID = 57 //UdpUpGameOver
)

// Enum value maps for CSID.
var (
	CSID_name = map[int32]string{
		1:  "TCP_LOGIN",
		10: "TCP_REQUEST_MATCH",
		11: "TCP_CANCEL_MATCH",
		51: "UDP_BATTLE_READY",
		53: "UDP_UP_PLAYER_OPERATIONS",
		55: "UDP_UP_DELTA_FRAMES",
		57: "UDP_UP_GAME_OVER",
	}
	CSID_value = map[string]int32{
		"TCP_LOGIN":                1,
		"TCP_REQUEST_MATCH":        10,
		"TCP_CANCEL_MATCH":         11,
		"UDP_BATTLE_READY":         51,
		"UDP_UP_PLAYER_OPERATIONS": 53,
		"UDP_UP_DELTA_FRAMES":      55,
		"UDP_UP_GAME_OVER":         57,
	}
)

func (x CSID) Enum() *CSID {
	p := new(CSID)
	*p = x
	return p
}

func (x CSID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CSID) Descriptor() protoreflect.EnumDescriptor {
	return file_PBCommon_proto_enumTypes[0].Descriptor()
}

func (CSID) Type() protoreflect.EnumType {
	return &file_PBCommon_proto_enumTypes[0]
}

func (x CSID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CSID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CSID(num)
	return nil
}

// Deprecated: Use CSID.Descriptor instead.
func (CSID) EnumDescriptor() ([]byte, []int) {
	return file_PBCommon_proto_rawDescGZIP(), []int{0}
}

type SCID int32

const (
	SCID_TCP_RESPONSE_LOGIN         SCID = 1  //TcpResponseLogin
	SCID_TCP_RESPONSE_REQUEST_MATCH SCID = 10 //TcpResponseRequestMatch
	SCID_TCP_RESPONSE_CANCEL_MATCH  SCID = 11 //TcpResponseCancelMatch
	SCID_TCP_ENTER_BATTLE           SCID = 50 //TcpEnterBattle
	SCID_UDP_BATTLE_START           SCID = 51 //UdpBattleStart
	SCID_UDP_DOWN_FRAME_OPERATIONS  SCID = 53 //UdpDownFrameOperations
	SCID_UDP_DOWN_DELTA_FRAMES      SCID = 55 //UdpDownDeltaFrames
	SCID_UDP_DOWN_GAME_OVER         SCID = 57 //UdpDownGameOver
)

// Enum value maps for SCID.
var (
	SCID_name = map[int32]string{
		1:  "TCP_RESPONSE_LOGIN",
		10: "TCP_RESPONSE_REQUEST_MATCH",
		11: "TCP_RESPONSE_CANCEL_MATCH",
		50: "TCP_ENTER_BATTLE",
		51: "UDP_BATTLE_START",
		53: "UDP_DOWN_FRAME_OPERATIONS",
		55: "UDP_DOWN_DELTA_FRAMES",
		57: "UDP_DOWN_GAME_OVER",
	}
	SCID_value = map[string]int32{
		"TCP_RESPONSE_LOGIN":         1,
		"TCP_RESPONSE_REQUEST_MATCH": 10,
		"TCP_RESPONSE_CANCEL_MATCH":  11,
		"TCP_ENTER_BATTLE":           50,
		"UDP_BATTLE_START":           51,
		"UDP_DOWN_FRAME_OPERATIONS":  53,
		"UDP_DOWN_DELTA_FRAMES":      55,
		"UDP_DOWN_GAME_OVER":         57,
	}
)

func (x SCID) Enum() *SCID {
	p := new(SCID)
	*p = x
	return p
}

func (x SCID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SCID) Descriptor() protoreflect.EnumDescriptor {
	return file_PBCommon_proto_enumTypes[1].Descriptor()
}

func (SCID) Type() protoreflect.EnumType {
	return &file_PBCommon_proto_enumTypes[1]
}

func (x SCID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SCID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SCID(num)
	return nil
}

// Deprecated: Use SCID.Descriptor instead.
func (SCID) EnumDescriptor() ([]byte, []int) {
	return file_PBCommon_proto_rawDescGZIP(), []int{1}
}

type TeamType int32

const (
	TeamType_NO    TeamType = 0
	TeamType_TEAM1 TeamType = 1
	TeamType_TEAM2 TeamType = 2
	TeamType_TEAM3 TeamType = 3
	TeamType_TEAM4 TeamType = 4
)

// Enum value maps for TeamType.
var (
	TeamType_name = map[int32]string{
		0: "NO",
		1: "TEAM1",
		2: "TEAM2",
		3: "TEAM3",
		4: "TEAM4",
	}
	TeamType_value = map[string]int32{
		"NO":    0,
		"TEAM1": 1,
		"TEAM2": 2,
		"TEAM3": 3,
		"TEAM4": 4,
	}
)

func (x TeamType) Enum() *TeamType {
	p := new(TeamType)
	*p = x
	return p
}

func (x TeamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamType) Descriptor() protoreflect.EnumDescriptor {
	return file_PBCommon_proto_enumTypes[2].Descriptor()
}

func (TeamType) Type() protoreflect.EnumType {
	return &file_PBCommon_proto_enumTypes[2]
}

func (x TeamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TeamType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TeamType(num)
	return nil
}

// Deprecated: Use TeamType.Descriptor instead.
func (TeamType) EnumDescriptor() ([]byte, []int) {
	return file_PBCommon_proto_rawDescGZIP(), []int{2}
}

var File_PBCommon_proto protoreflect.FileDescriptor

var file_PBCommon_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x50, 0x42, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x2a, 0xa5, 0x01, 0x0a, 0x04, 0x43, 0x53, 0x49, 0x44, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x43, 0x50, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x54, 0x43, 0x50, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4d, 0x41, 0x54, 0x43,
	0x48, 0x10, 0x0a, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x43, 0x50, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x0b, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x44, 0x50,
	0x5f, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x33, 0x12,
	0x1c, 0x0a, 0x18, 0x55, 0x44, 0x50, 0x5f, 0x55, 0x50, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x35, 0x12, 0x17, 0x0a,
	0x13, 0x55, 0x44, 0x50, 0x5f, 0x55, 0x50, 0x5f, 0x44, 0x45, 0x4c, 0x54, 0x41, 0x5f, 0x46, 0x52,
	0x41, 0x4d, 0x45, 0x53, 0x10, 0x37, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x44, 0x50, 0x5f, 0x55, 0x50,
	0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x39, 0x2a, 0xdb, 0x01, 0x0a,
	0x04, 0x53, 0x43, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x43, 0x50, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x1e, 0x0a,
	0x1a, 0x54, 0x43, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x0a, 0x12, 0x1d, 0x0a,
	0x19, 0x54, 0x43, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x43, 0x41,
	0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x0b, 0x12, 0x14, 0x0a, 0x10,
	0x54, 0x43, 0x50, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45,
	0x10, 0x32, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x44, 0x50, 0x5f, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x33, 0x12, 0x1d, 0x0a, 0x19, 0x55, 0x44, 0x50, 0x5f,
	0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x35, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x44, 0x50, 0x5f, 0x44,
	0x4f, 0x57, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x54, 0x41, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x53,
	0x10, 0x37, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x44, 0x50, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x39, 0x2a, 0x3e, 0x0a, 0x08, 0x54, 0x65,
	0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x54, 0x45, 0x41, 0x4d, 0x31, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x45, 0x41,
	0x4d, 0x32, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x45, 0x41, 0x4d, 0x33, 0x10, 0x03, 0x12,
	0x09, 0x0a, 0x05, 0x54, 0x45, 0x41, 0x4d, 0x34, 0x10, 0x04, 0x42, 0x02, 0x48, 0x03,
}

var (
	file_PBCommon_proto_rawDescOnce sync.Once
	file_PBCommon_proto_rawDescData = file_PBCommon_proto_rawDesc
)

func file_PBCommon_proto_rawDescGZIP() []byte {
	file_PBCommon_proto_rawDescOnce.Do(func() {
		file_PBCommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_PBCommon_proto_rawDescData)
	})
	return file_PBCommon_proto_rawDescData
}

var file_PBCommon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_PBCommon_proto_goTypes = []interface{}{
	(CSID)(0),     // 0: pb.CSID
	(SCID)(0),     // 1: pb.SCID
	(TeamType)(0), // 2: pb.TeamType
}
var file_PBCommon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PBCommon_proto_init() }
func file_PBCommon_proto_init() {
	if File_PBCommon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PBCommon_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PBCommon_proto_goTypes,
		DependencyIndexes: file_PBCommon_proto_depIdxs,
		EnumInfos:         file_PBCommon_proto_enumTypes,
	}.Build()
	File_PBCommon_proto = out.File
	file_PBCommon_proto_rawDesc = nil
	file_PBCommon_proto_goTypes = nil
	file_PBCommon_proto_depIdxs = nil
}
